name: egingapp
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.1
dependencies:
  flutter:
    sdk: flutter
  firebase_app_check: ^0.3.0
  cupertino_icons: ^1.0.8
  firebase_core: ^3.15.0
  firebase_auth: ^5.6.1
  google_sign_in: ^7.1.0
  geolocator: ^14.0.2
  google_maps_flutter: ^2.12.3
  sign_in_with_apple: ^6.1.1
  image_picker: ^1.1.2
  firebase_storage: ^12.4.9
  cloud_firestore: ^5.6.11
  image: ^4.5.4
  file_picker: ^10.2.0
  intl: ^0.20.2
  geocoding: ^3.0.0
  fl_chart: ^0.68.0
  shared_preferences: ^2.5.2
  smooth_page_indicator: ^1.1.0
  rxdart: ^0.27.3
  timeago: ^3.7.1
  firebase_messaging: ^15.0.1
  flutter_local_notifications: ^17.2.1
  flutter_riverpod: ^2.5.1
  algolia_helper_flutter: ^1.2.0
  equatable: ^2.0.5
  cached_network_image: ^3.3.1
  collection: ^1.19.1
  camera: ^0.11.0
  webview_flutter: ^4.13.0
  url_launcher: ^6.2.6 

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.11
  riverpod_generator: ^2.4.1
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/index.html
    - assets/2025-10_cooking_contest_lp.html
    - assets/2025-10_number_contest_lp.html
    - assets/2025-10_size_contest_lp.html
    - assets/2025-10_tackle_contest_lp.html

