// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCffqvrdwB5AF6tUlReNp0naREe8rMXlaA',
    appId: '1:211367399364:web:05e852bf1bf1bcbfc95e91',
    messagingSenderId: '211367399364',
    projectId: 'eging-map-app',
    authDomain: 'eging-map-app.firebaseapp.com',
    storageBucket: 'eging-map-app.firebasestorage.app',
    measurementId: 'G-TT1F1Q288Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJPIIu4BUSHQdKwA5IDg3HvRrxp0TO1s8',
    appId: '1:211367399364:android:0c2c6aee58933d42c95e91',
    messagingSenderId: '211367399364',
    projectId: 'eging-map-app',
    storageBucket: 'eging-map-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlnN-AyZHz6aIUFsn8kZZ62__AEu1NfQM',
    appId: '1:211367399364:ios:8fa5bb12e2544974c95e91',
    messagingSenderId: '211367399364',
    projectId: 'eging-map-app',
    storageBucket: 'eging-map-app.firebasestorage.app',
    iosBundleId: 'com.example.egingapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlnN-AyZHz6aIUFsn8kZZ62__AEu1NfQM',
    appId: '1:211367399364:ios:8fa5bb12e2544974c95e91',
    messagingSenderId: '211367399364',
    projectId: 'eging-map-app',
    storageBucket: 'eging-map-app.firebasestorage.app',
    iosBundleId: 'com.example.egingapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCffqvrdwB5AF6tUlReNp0naREe8rMXlaA',
    appId: '1:211367399364:web:b06a35d964483cd2c95e91',
    messagingSenderId: '211367399364',
    projectId: 'eging-map-app',
    authDomain: 'eging-map-app.firebaseapp.com',
    storageBucket: 'eging-map-app.firebasestorage.app',
    measurementId: 'G-VEZXQQJP5N',
  );
}
